version: "3.8"

services:
  goapp:
    build:
      context: .
      dockerfile: ./bin/golang/Dockerfile
    container_name: "${COMPOSE_PROJECT_NAME}-goapp"
    ports:
      - "8090:8090"
    environment:
      MONGO_ADDR: ${MONGODB_ADDR}
      MONGO_USER: ${MONGODB_USER}
      MONGO_PASS: ${MONGODB_PASSWORD}
      MONGO_DATABASE: ${MONGODB_DATABASE}
      SERVER_ADDR: ${SERVER_ADDR}
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: "${COMPOSE_PROJECT_NAME}-mongodb"
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_DATABASE: ${MONGODB_DATABASE}

  webserver:
    build:
      context: ./bin/${PHPVERSION}
    container_name: "${COMPOSE_PROJECT_NAME}-${PHPVERSION}"
    restart: "always"
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
      - "${HOST_MACHINE_SECURE_HOST_PORT}:443"
    volumes:
      - ${DOCUMENT_ROOT-./www}:/var/www/html:rw
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${SSL_DIR-./config/ssl}:/etc/apache2/ssl/
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
      - ${XDEBUG_LOG_DIR-./logs/xdebug}:/var/log/xdebug
      - ${ASUS_KEY_PATH-./config/asus}:/var/www/config/asus
    environment:
      APACHE_DOCUMENT_ROOT: ${APACHE_DOCUMENT_ROOT-/var/www/html}
      PMA_PORT: ${HOST_MACHINE_PMA_PORT}
      XDEBUG_CONFIG: "client_host=host.docker.internal remote_port=${XDEBUG_PORT}"
      TZ: Asia/Taipei
      ASUS_API_ID: ${ASUS_API_ID}
      ASUS_SOURCE_DOMAIN: ${ASUS_SOURCE_DOMAIN}
      ASUS_SUB_KEY: ${ASUS_SUB_KEY}
      ASUS_AUTH_TOKEN: ${ASUS_AUTH_TOKEN}
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  heweb:
    build:
      context: ./bin/heweb
    container_name: "${COMPOSE_PROJECT_NAME}-heweb"
    ports:
      - "4200:80"
    volumes:
      - ./bin/heweb/heweb-app/browser:/usr/share/nginx/html:ro
    depends_on:
      - goapp

volumes:
  mongodb-data:
