server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Redirect root to index.html
    location = / {
        return 301 /index.html;
    }
    error_page 404 /index.html;
}
